# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{android-adb}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nic Strong"]
  s.date = %q{2011-05-03}
  s.email = %q{nic.strong@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "android-adb.gemspec",
    "examples/listdevices.rb",
    "examples/listpackages.rb",
    "examples/showcmds.rb",
    "lib/android-adb.rb",
    "lib/android-adb/Adb.rb",
    "lib/android-adb/Device.rb",
    "lib/android-adb/Package.rb",
    "lib/android-adb/version.rb"
  ]
  s.homepage = %q{http://github.com/nicstrong/android-adb}
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby bindings for the Android SDK adb command.}
  s.test_files = [
    "examples/listdevices.rb",
    "examples/listpackages.rb",
    "examples/showcmds.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<Platform>, [">= 0.4.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.8"])
    else
      s.add_dependency(%q<Platform>, [">= 0.4.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<yard>, [">= 0.6.8"])
    end
  else
    s.add_dependency(%q<Platform>, [">= 0.4.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<yard>, [">= 0.6.8"])
  end
end

